import { mkdir, readFile, rm, rmdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { UPWIND_AUTH_BASE_PATH } from '@stayingupwind/core/paas';

import type { AuthLayout } from './layout.ts';

/**
 * The route that serves `/__upwind/auth`, written for a project that has an auth config.
 *
 * Next.js has no way for an adapter to contribute a route — `modifyConfig` and `onBuildComplete` are
 * the whole of the Adapter API, and neither adds one — and `auth.ts` deliberately does not live under
 * `app`, because it sits beside `proxy.ts` where a project's other root files are. So the only way to
 * have Next.js *build* the handler is for the file to be there, and the only way for it to be there
 * without anybody writing it is this.
 *
 * Which makes this the one thing in upwind that writes source into somebody's project. The rules it
 * is held to follow from that:
 *
 * - **It is the developer's file.** Committed, edited, moved — all fine. A file whose contents are
 *   not exactly what this would write is one somebody took over, and it is never touched again.
 * - **It is written back.** `upwind dev` and `upwind build` both ensure it, so a project that
 *   gitignores it still builds in CI, and a project that deleted it by accident gets it back.
 * - **It goes when the config goes.** A route importing an `auth.ts` that is no longer there would
 *   fail the build with a message about an import nobody wrote. So a generated route with no config
 *   beside it is removed — and only ever a generated one, by the same exact-contents test.
 * - **It never fails a run.** A project on a read-only checkout, or one where the path is taken by
 *   something else, gets a warning and a dev server. `agent-rules.ts` takes the same view of the
 *   same kind of work.
 */

/**
 * The route's own path under `app`, as directories rather than as the URL they serve.
 *
 * `%5F%5Fupwind`, and it has to be: a folder whose name begins with an underscore is a *private*
 * folder to Next.js — opted out of routing entirely, along with everything under it — so a directory
 * literally called `__upwind` builds nothing and answers 404. `%5F` is Next.js's own escape for a
 * URL segment that starts with an underscore, and `%5F%5Fupwind` is what serves `/__upwind`.
 */
const ROUTE_SEGMENTS: readonly string[] = ['%5F%5Fupwind', 'auth', '[...all]'];

/**
 * How far the route sits below the directory the config shares with `app`: one for each segment
 * above, and one for `app` itself. Derived rather than written as `../../../..`, so that a segment
 * added above moves the import with it.
 */
const UP_TO_ROOT = '../'.repeat(ROUTE_SEGMENTS.length + 1);

/**
 * What the file says.
 *
 * Plain JavaScript that is also valid TypeScript, so the same text serves a project of either kind
 * and the only difference between them is the extension it is saved under. It says nothing about the
 * config file it imports beyond the extensionless specifier, which is what makes the exact-contents
 * test below decidable: a project that renames `auth.ts` to `auth.tsx` does not thereby own a file it
 * has never opened.
 *
 * `dynamic` is set rather than left to inference. Next.js decides a route handler is dynamic when it
 * sees the request being used, and this one does use it — but a handler that was ever decided the
 * other way would be an authentication endpoint answered from a cache, which is not the kind of
 * mistake to leave to an inference that lives in somebody else's release.
 */
const SOURCE = `// Generated by upwind, because this project has an auth config beside its app.
//
// It mounts that config at ${UPWIND_AUTH_BASE_PATH}. Nothing here is precious: commit it, edit it,
// or delete the auth config and this file goes too. Once you have changed it, upwind leaves it alone.
import { toNextHandler } from '@stayingupwind/auth/next';

import * as config from '${UP_TO_ROOT}auth';

export const dynamic = 'force-dynamic';

export const { GET, POST } = toNextHandler(config);
`;

/** Where the route goes for a project whose `app` is this one. */
function routeFile(appDir: string, typescript: boolean): string {
  return path.join(appDir, ...ROUTE_SEGMENTS, typescript ? 'route.ts' : 'route.js');
}

/**
 * What is there now, or nothing for a file that is not there.
 *
 * Only absence answers `undefined`. Everything else is raised, and `prepareAuth` turns it into a
 * warning and a run with no route (`prepare.ts`) — because the whole rule here rests on this answer:
 * "nothing is there" is what allows a write, and a file that merely could not be *read* is still a
 * file somebody owns. Treating a permissions error as absence would mean overwriting it wherever the
 * directory happened to be writable.
 */
async function contentsOf(file: string): Promise<string | undefined> {
  try {
    return await readFile(file, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return undefined;
    }
    throw error;
  }
}

/**
 * Remove a route this wrote, for a project whose auth config has gone.
 *
 * Only an exact match is removed. Anything else is a file somebody else is responsible for, and this
 * has no business deleting it — including one that no version of this has ever written, which is what
 * an unrelated route at the same path would be. Both extensions are looked at, since a project that
 * moved from JavaScript to TypeScript has the older one still standing.
 */
async function removeGenerated(appDir: string): Promise<void> {
  let removed = false;
  for (const typescript of [true, false]) {
    const file = routeFile(appDir, typescript);
    if ((await contentsOf(file)) !== SOURCE) {
      continue;
    }
    try {
      await rm(file, { force: true });
      removed = true;
    } catch {
      // Gone already, or not this run's to remove. Either way there is nothing left to do about it.
    }
  }
  if (!removed) {
    return;
  }
  // The directories it stood in are the ones this made. `rmdir` refuses a directory that still holds
  // something, which is exactly the test wanted: whatever else is in there is somebody's.
  for (let depth = ROUTE_SEGMENTS.length; depth > 0; depth -= 1) {
    try {
      await rmdir(path.join(appDir, ...ROUTE_SEGMENTS.slice(0, depth)));
    } catch {
      break;
    }
  }
}

/**
 * Make sure `/__upwind/auth` is served, or make sure nothing claims to serve it.
 *
 * Called before Next.js is started and before a build is spawned, because the route has to be on
 * disk when the bundler reads the project — not when the first request arrives.
 */
export async function ensureAuthRoute(
  projectDir: string,
  layout: AuthLayout | undefined,
): Promise<void> {
  if (layout === undefined) {
    // Both places `app` can be, since the project that had a config may have moved it since.
    await removeGenerated(path.join(projectDir, 'app'));
    await removeGenerated(path.join(projectDir, 'src', 'app'));
    return;
  }
  if (layout.appDir === undefined) {
    // A Pages-Router-only project. The handler would have to be a different shape (`toNodeHandler`,
    // `bodyParser: false`), and writing an App Router route into a project that has no `app` would
    // change what Next.js builds rather than add to it. Said, and left to the developer.
    console.warn(
      `upwind: ${layout.configFile} is an auth config, but this project has no \`app\` directory — mount it yourself, or give the config a base path of its own and ${UPWIND_AUTH_BASE_PATH} stops being upwind's to serve`,
    );
    return;
  }
  // A route of the other language first, because two of them in one directory is not a project
  // Next.js will build: `route.ts` and `route.js` both claim the segment. A project that moved from
  // JavaScript to TypeScript has the older one standing, and it is this that put it there — so this
  // takes it back. One somebody else wrote is a different matter: they have mounted this path
  // themselves, and the right thing is to add nothing beside it.
  const stale = routeFile(layout.appDir, !layout.typescript);
  const beside = await contentsOf(stale);
  if (beside === SOURCE) {
    try {
      await rm(stale, { force: true });
    } catch {
      // Still there, and about to be joined by its replacement. Next.js will say so more clearly
      // than this could, and naming the one that could not be removed is all there is to add.
      console.warn(`upwind: could not remove ${stale}, which the route beside it now replaces`);
    }
  } else if (beside !== undefined) {
    return;
  }
  const file = routeFile(layout.appDir, layout.typescript);
  const existing = await contentsOf(file);
  if (existing !== undefined) {
    // Already ours and unchanged, or theirs now. Neither is written to, and neither is spoken about:
    // a developer who edited this file did so on purpose, and a warning every time a dev server
    // starts is not a conversation.
    return;
  }
  try {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, SOURCE);
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    console.warn(
      `upwind: could not write ${file}, so ${UPWIND_AUTH_BASE_PATH} is served by whatever is there now (${reason})`,
    );
  }
}
