/**
 * `next/dist/compiled/raw-body`, as a Function can load it.
 *
 * The Pages Router's API body parser reads the request through `raw-body`, and the copy Next.js
 * compiles in bundles `depd`, whose deprecation wrapper builds a function from a string: workerd
 * refuses that at load (`EvalError: Code generation from strings disallowed`), and the parser
 * answers every request with `400 Invalid body`. This copy reads the stream the same way — the
 * `limit`, `length` and `encoding` options, the promise and callback forms, the errors with the
 * `type` and `status` the parser reads — decoding with `TextDecoder`, which is what the Function
 * has in place of `iconv-lite`.
 */

export const RAW_BODY_MODULE = /(?:^|\/)compiled\/raw-body$/u;

export const RAW_BODY_SOURCE = [
  "'use strict';",
  'const UNITS = { b: 1, kb: 1024, mb: 1048576, gb: 1073741824, tb: 1099511627776, pb: 1125899906842624 };',
  'function parseBytes(value) {',
  '  if (typeof value === "number") { return Number.isFinite(value) ? value : null; }',
  '  if (typeof value !== "string") { return null; }',
  String.raw`  const match = /^([-+]?\d+(?:\.\d+)?) *(kb|mb|gb|tb|pb)?$/i.exec(value.trim());`,
  '  if (match === null) { return null; }',
  '  return Math.floor(parseFloat(match[1]) * UNITS[(match[2] || "b").toLowerCase()]);',
  '}',
  'function httpError(status, message, props) {',
  '  const error = new Error(message);',
  '  error.status = status;',
  '  error.statusCode = status;',
  '  error.expose = status < 500;',
  '  return Object.assign(error, props);',
  '}',
  'function parseLength(value) {',
  '  if (value === undefined || value === null) { return null; }',
  '  const length = parseInt(value, 10);',
  '  return Number.isNaN(length) ? null : length;',
  '}',
  'function readStream(stream, options) {',
  '  return new Promise((resolve, reject) => {',
  '    const limit = parseBytes(options.limit);',
  '    const length = parseLength(options.length);',
  '    const encoding = options.encoding === true ? "utf-8" : options.encoding;',
  '    let decoder = null;',
  '    if (encoding) {',
  '      try {',
  '        decoder = new TextDecoder(encoding);',
  '      } catch (error) {',
  '        reject(httpError(415, "specified encoding unsupported", { encoding, type: "encoding.unsupported" }));',
  '        return;',
  '      }',
  '    }',
  '    if (limit !== null && length !== null && length > limit) {',
  '      reject(httpError(413, "request entity too large", { expected: length, length, limit, type: "entity.too.large" }));',
  '      return;',
  '    }',
  '    const chunks = [];',
  '    let received = 0;',
  '    let settled = false;',
  '    const cleanup = () => {',
  '      stream.removeListener("data", onData);',
  '      stream.removeListener("end", onEnd);',
  '      stream.removeListener("aborted", onAborted);',
  '      stream.removeListener("error", onError);',
  '      stream.removeListener("close", onClose);',
  '    };',
  '    const finish = (error, body) => {',
  '      if (settled) { return; }',
  '      settled = true;',
  '      cleanup();',
  '      if (error) {',
  '        if (typeof stream.destroy === "function") { stream.destroy(); }',
  '        reject(error);',
  '      } else {',
  '        resolve(body);',
  '      }',
  '    };',
  '    const onData = (chunk) => {',
  '      const buffer = typeof chunk === "string" ? Buffer.from(chunk) : chunk;',
  '      received += buffer.length;',
  '      if (limit !== null && received > limit) {',
  '        finish(httpError(413, "request entity too large", { limit, received, type: "entity.too.large" }));',
  '        return;',
  '      }',
  '      chunks.push(buffer);',
  '    };',
  '    const onEnd = () => {',
  '      if (length !== null && received !== length) {',
  '        finish(httpError(400, "request size did not match content length", { expected: length, length, received, type: "request.size.invalid" }));',
  '        return;',
  '      }',
  '      const body = Buffer.concat(chunks, received);',
  '      finish(null, decoder === null ? body : decoder.decode(body));',
  '    };',
  '    const onAborted = () => {',
  '      finish(httpError(400, "request aborted", { code: "ECONNABORTED", expected: length, length, received, type: "request.aborted" }));',
  '    };',
  '    const onError = (error) => { finish(error); };',
  '    const onClose = () => { onAborted(); };',
  '    stream.on("data", onData);',
  '    stream.on("end", onEnd);',
  '    stream.on("aborted", onAborted);',
  '    stream.on("error", onError);',
  '    stream.on("close", onClose);',
  '  });',
  '}',
  'function getRawBody(stream, options, callback) {',
  '  let done = callback;',
  '  let opts = options;',
  '  if (options === true || typeof options === "string") { opts = { encoding: options }; }',
  '  if (typeof options === "function") { done = options; opts = {}; }',
  '  const promise = readStream(stream, opts || {});',
  '  if (typeof done !== "function") { return promise; }',
  '  promise.then((body) => done(null, body), (error) => done(error));',
  '  return undefined;',
  '}',
  'module.exports = getRawBody;',
  '',
].join('\n');
