import { writeFile } from 'node:fs/promises';
import path from 'node:path';

import { type InputOptions, type OutputChunk, rolldown } from 'rolldown';

import { bundled, type BundleTrace } from './dependencies.ts';
import { dynamicLoadsInChunk } from './dynamic-loads.ts';
import { externalsPlugin, WORKER_BANNER } from './patches/index.ts';

/**
 * The Worker's second bundle: the entrypoints `next build` put on Next.js's deprecated edge
 * runtime.
 *
 * Such an entrypoint is not a module the Worker can require. Turbopack builds it into chunks that
 * register a Web handler in the global edge entry registry as they are evaluated, and Next.js
 * names the registration in `output.edgeRuntime` — `modulePath`, `entryKey`, `handlerExport` —
 * which is the documented way to reach one (Adapters, "Invoking Entrypoints"). The chunk loader
 * in those chunks reads no files at run time (`loadChunkCached` throws), so evaluating every
 * chunk of an entry is the whole of loading it, and nothing here needs the chunk-table rewrite
 * the Node.js build needs.
 *
 * It is a bundle of its own, and not part of `app.cjs`, because the two are compiled for
 * different runtimes: `app.cjs` is built with `process.env.NEXT_RUNTIME` pinned to `"nodejs"`,
 * which is exactly the test the edge code branches on.
 *
 * Like `app.cjs`, it is a table of thunks: the module the Worker loads at startup is the table,
 * and an entry's chunks are evaluated by the first request that needs them. A deployment with no
 * edge entrypoint has no such module at all.
 */

export interface EdgeEntry {
  /** Key the runtime asks for: the route's pathname, or `/_middleware`. */
  readonly id: string;
  /** Name the entry registers itself under in `globalThis._ENTRIES`. */
  readonly entryKey: string;
  /** Export of the registered entry to invoke (`handler`). */
  readonly handlerExport: string;
  /** Absolute paths of the chunks to evaluate, in the order Next.js lists them. */
  readonly files: readonly string[];
  /**
   * The WebAssembly those chunks read, by the global they read it from. Nothing here loads it:
   * the Worker publishes each global before a request reaches a thunk (see `wasm.ts`), which is
   * the contract Turbopack's edge loader was compiled against.
   */
  readonly wasm: readonly { global: string; filePath: string }[];
  /** Build-time environment the entry is compiled against (`__NEXT_BUILD_ID`, preview mode ids). */
  readonly env: Readonly<Record<string, string>>;
}

export const EDGE_MODULE = 'edge.cjs';

/**
 * The generated entry: one thunk per entrypoint, each evaluating its chunks and handing back the
 * handler the registry then holds.
 *
 * The environment is applied first and over what the Worker already has, as Next.js's own edge
 * runtime applies it: these are constants of the build the chunks were compiled against (the
 * build id, the preview mode ids, the key Server Actions are encrypted with), and a Worker
 * binding of the same name from another build would not match the code.
 */
export function edgeEntrySource(entries: readonly EdgeEntry[]): string {
  const table = entries.map((entry) => {
    const env = JSON.stringify(entry.env);
    return [
      `    ${JSON.stringify(entry.id)}: () => {`,
      ...(Object.keys(entry.env).length === 0 ? [] : [`      Object.assign(process.env, ${env});`]),
      ...entry.files.map((file) => `      require(${JSON.stringify(file)});`),
      `      return registered(${JSON.stringify(entry.entryKey)}, ${JSON.stringify(entry.handlerExport)});`,
      '    },',
    ].join('\n');
  });
  return [
    '// Generated by @upwind/adapter: the entrypoints `next build` built for the edge runtime.',
    'function registered(key, handlerExport) {',
    '  const entry = globalThis._ENTRIES?.[key];',
    '  if (entry === undefined) {',
    "    throw new Error('@upwind/adapter: ' + key + ' registered no edge entry');",
    '  }',
    '  return { handler: entry[handlerExport] };',
    '}',
    'module.exports = {',
    '  entries: {',
    ...table,
    '  },',
    '};',
    '',
  ].join('\n');
}

/**
 * How the edge bundle is built. The Turbopack output it carries is self-contained — every
 * dependency is already inlined for the edge target — so the only plugin is the one that reports
 * what is left to the Worker's own resolver, for the audit to refuse. Whatever Rolldown cannot
 * resolve is reported the same way, as in `appBundleOptions`.
 */
export function edgeBundleOptions(
  projectDir: string,
  entryFile: string,
  onExternal: (specifier: string) => void,
): InputOptions {
  return {
    cwd: projectDir,
    input: entryFile,
    // Node built-ins, with or without the `node:` prefix, are the Worker's own to resolve.
    platform: 'node',
    plugins: [externalsPlugin(onExternal)],
    transform: {
      define: {
        'process.env.NEXT_RUNTIME': '"edge"',
        'process.env.NODE_ENV': '"production"',
      },
    },
    onLog(_level, log) {
      if (log.code === 'UNRESOLVED_IMPORT' && log.exporter !== undefined) {
        onExternal(log.exporter);
      }
    },
  };
}

export interface BundleEdgeInput {
  readonly kind: string;
  readonly projectDir: string;
  readonly workDir: string;
  readonly entries: readonly EdgeEntry[];
}

export async function bundleEdge(
  input: BundleEdgeInput,
): Promise<{ outFile: string; trace: BundleTrace }> {
  const entryFile = path.join(input.workDir, `${input.kind}-edge-entry.cjs`);
  const outFile = path.join(input.workDir, `${input.kind}-${EDGE_MODULE}`);
  await writeFile(entryFile, edgeEntrySource(input.entries));
  const externals = new Set<string>();
  await using bundle = await rolldown(
    edgeBundleOptions(input.projectDir, entryFile, (specifier) => externals.add(specifier)),
  );
  const { output } = await bundle.write({
    format: 'cjs',
    file: outFile,
    // Next.js's storages read `globalThis.AsyncLocalStorage` once, as they do in `app.cjs`, and
    // workerd has it only under `node:async_hooks`.
    banner: WORKER_BANNER,
    minify: { compress: true, mangle: false, codegen: { removeWhitespace: true } },
    comments: { legal: false },
    sourcemap: false,
  });
  const chunk = output.find((item): item is OutputChunk => item.type === 'chunk');
  if (chunk === undefined) {
    throw new Error(`@upwind/adapter: the ${input.kind} Worker's edge bundle made no chunk`);
  }
  return {
    outFile,
    trace: {
      inputs: Object.entries(chunk.modules).map(([file, module]) => bundled(file, module)),
      externals: [...externals],
      patches: [],
      stubs: [],
      // Nothing here resolves a `.wasm`: Turbopack inlined every dependency of an edge
      // entrypoint, and what its chunks read they read off a global. Which global, and from
      // which file, is what Next.js named in `wasmAssets` — recorded so a deployment's
      // WebAssembly is in the record whichever runtime asked for it.
      wasmModules: input.entries.flatMap((entry) =>
        entry.wasm.map((asset) => `${asset.filePath} -> ${asset.global}`),
      ),
      dynamicLoads: dynamicLoadsInChunk(chunk),
    },
  };
}
