import { mkdir, writeFile } from 'node:fs/promises';
import path from 'node:path';

import { jsLiteral } from './codegen.ts';

/**
 * The instrumentation hook a Function runs, when the host has one of its own to add.
 *
 * Next.js loads one hook per server, from one file. A host that wants to see what an application
 * does — errors as they are thrown, a span as a request is served — has nowhere to put that
 * without taking the file away from the project, whose own hook is the documented way for an
 * application to instrument itself. So the adapter generates a module that is both: it requires
 * the host's modules and the project's hook, and composes each exported hook so that both run.
 *
 * Three rules, and they are all in the order and the error handling below:
 *
 * - the host runs first, because what it is usually there for is to see a failure the project's
 *   own hook might swallow;
 * - the host's call is wrapped, so a host whose hook throws cannot change what the application
 *   does — the project asked Next.js for its hook, not for the host's;
 * - the project's call is not wrapped, because it is the application's own code and Next.js's
 *   handling of it is the behaviour the project expects.
 *
 * A project with no hook of its own is the same module with nothing to delegate to, which is why
 * this is generated even then: Next.js's loader requires one path, and a host's hook has to be
 * behind it.
 */

/** The generated module's name under the build's own directory. */
const MODULE_NAME = 'instrumentation.cjs';

/** Hooks composed by calling every implementation; each returns nothing a caller reads. */
const COMPOSED_HOOKS = ['register', 'onRequestError'] as const;

/**
 * Each host module, loaded inside a `try`.
 *
 * A module that throws while it is being evaluated would otherwise take the whole Function down
 * with it: this runs at the top of the generated hook, which Next.js requires before any
 * entrypoint. A host that cannot even load is a host that sees nothing, which is the same
 * outcome as a host that was never configured — and is the application's to survive.
 */
function requireList(modules: readonly string[]): string {
  return modules
    .map((module) => {
      return [
        '  (() => {',
        '    try {',
        `      return require(${jsLiteral(module)});`,
        '    } catch (error) {',
        `      console.error("upwind: a host's instrumentation could not be loaded", error);`,
        '      return undefined;',
        '    }',
        '  })(),',
      ].join('\n');
    })
    .join('\n');
}

function composition(hook: string): string {
  return [
    `  ${hook}: async (...args) => {`,
    '    for (const module of hosts) {',
    `      if (typeof module?.${hook} === 'function') {`,
    '        try {',
    `          await module.${hook}(...args);`,
    '        } catch (error) {',
    "          // A host's own hook must not change what the application does.",
    `          console.error("upwind: the host's ${hook} failed", error);`,
    '        }',
    '      }',
    '    }',
    `    if (typeof own?.${hook} === 'function') {`,
    `      return own.${hook}(...args);`,
    '    }',
    '    return undefined;',
    '  },',
  ].join('\n');
}

export interface ComposedInstrumentationInput {
  /** Where the generated module is written; the build's own output directory. */
  readonly outDir: string;
  /** The project's compiled hook, when it wrote one. */
  readonly own: string | undefined;
  /** The host's modules, in the order it gave them. */
  readonly hosts: readonly string[];
}

/**
 * Write the composed hook and answer its path, or answer the project's own when the host added
 * nothing — a build with no host module needs no module in front of the project's.
 */
export async function composedInstrumentation(
  input: ComposedInstrumentationInput,
): Promise<string | undefined> {
  if (input.hosts.length === 0) {
    return input.own;
  }
  const source = [
    '// Generated by @stayingupwind/adapter: the host’s instrumentation, and the project’s.',
    'const hosts = [',
    requireList(input.hosts),
    '];',
    input.own === undefined
      ? 'const own = undefined;'
      : `const own = require(${jsLiteral(input.own)});`,
    'module.exports = {',
    // Whatever else the project's hook exports stays reachable under its own name; only the hooks
    // below are composed, and they are written after the spread so they win.
    '  ...own,',
    ...COMPOSED_HOOKS.map((hook) => composition(hook)),
    '};',
    '',
  ].join('\n');
  await mkdir(input.outDir, { recursive: true });
  const file = path.join(input.outDir, MODULE_NAME);
  await writeFile(file, source);
  return file;
}

/** The generated browser module's name, and how `instrumentationClientInject` names it. */
const CLIENT_MODULE_NAME = 'client-instrumentation.js';

/**
 * Write the host's browser module into the build's own directory and answer the entry Next.js
 * resolves it by: a path relative to the project root, which is one of the two forms
 * `instrumentationClientInject` takes. The other is a package name in the project's
 * `node_modules`, which a host's module is not in — it is installed wherever the host's build
 * runs, which is outside the project altogether.
 */
export async function writeClientInstrumentation(input: {
  readonly outDir: string;
  readonly outDirName: string;
  readonly source: string;
}): Promise<string> {
  await mkdir(input.outDir, { recursive: true });
  await writeFile(path.join(input.outDir, CLIENT_MODULE_NAME), input.source);
  return `./${input.outDirName}/${CLIENT_MODULE_NAME}`;
}
