import { once } from 'node:events';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createGzip } from 'node:zlib';

import type { WorkerModule, WorkerSpec } from '@upwind/core/bundle';
import { build, type Plugin } from 'esbuild';
import {
  type InputOptions,
  type OutputChunk,
  type Plugin as RolldownPlugin,
  rolldown,
} from 'rolldown';

import { type BlobStore, contentTypeFor } from './blobs.ts';
import {
  auditWorker,
  auditWorkerSize,
  bundled,
  bundleDependencies,
  type BundleTrace,
  type WorkerDependencies,
  workerDependencies,
  type WorkerSize,
} from './dependencies.ts';
import { dynamicLoadsInChunk } from './dynamic-loads.ts';
import { bundleEdge, EDGE_MODULE, type EdgeEntry } from './edge.ts';
import type { TextModule } from './manifests.ts';
import {
  type AppliedPatch,
  externalsPlugin,
  OG_FONT_FILE,
  OG_FONT_MODULE,
  type PatchContext,
  PATCHES,
  patchesPlugin,
  stubPlugin,
  vendoredOtelPlugin,
  wasmModulePlugin,
  WORKER_BANNER,
} from './patches/index.ts';
import { WASM_ENTRY_MODULE, type WasmCollector, wasmEntrySource, wasmModuleName } from './wasm.ts';

/**
 * The runtime the user Worker is uploaded against. Pinned rather than following the platform's own
 * Workers: a deployment's semantics must not shift underneath it when the platform moves its date.
 */
const WORKER_COMPATIBILITY_DATE = '2026-09-15';
const WORKER_COMPATIBILITY_FLAGS: readonly string[] = ['nodejs_compat'];

const APP_MODULE = 'app.cjs';
const RUNTIME_MODULE = 'index.mjs';
const RUNTIME_MANIFEST_MODULE = 'runtime.json';
const BLOB_MODULE_PREFIX = 'blobs/';

export interface EntryModule {
  /** Key the runtime asks for (`/[locale]`, `/api/auth/[...all]`, `/_middleware`). */
  readonly id: string;
  /** Absolute path of the built module (`.next/server/app/[locale]/page.js`). */
  readonly filePath: string;
}

export interface BuildWorkerInput {
  readonly kind: 'app' | 'middleware';
  readonly projectDir: string;
  readonly outDir: string;
  readonly patch: PatchContext;
  readonly entries: readonly EntryModule[];
  /** The entrypoints `next build` put on the edge runtime; they go into a bundle of their own. */
  readonly edgeEntries: readonly EdgeEntry[];
  /** The WebAssembly this Worker carries, one module per distinct file (see `wasm.ts`). */
  readonly wasm: WasmCollector;
  readonly manifests: readonly TextModule[];
  /** Contents of `runtime.json`: what the runtime needs to know about the deployment. */
  readonly runtimeManifest: string;
  /** The module `ppr-cdn:cache-host` resolves to; a build given none gets no runtime cache. */
  readonly cacheHostModule: string | undefined;
  /** Blobs to ship inside the Worker (prerendered bodies and postponed states). */
  readonly blobs: readonly { sha256: string; bytes: Uint8Array }[];
  readonly blobStore: BlobStore;
}

/** Module name a blob is shipped under; the runtime reads it back at `/bundle/blobs/<sha256>`. */
function blobModuleName(sha256: string): string {
  return `${BLOB_MODULE_PREFIX}${sha256}`;
}

function appEntrySource(entries: readonly EntryModule[]): string {
  const table = entries
    .map(
      (entry) => `  ${JSON.stringify(entry.id)}: () => require(${JSON.stringify(entry.filePath)}),`,
    )
    .join('\n');
  return [
    '// Generated by @upwind/adapter: the entrypoints `next build` produced, by route.',
    'module.exports = {',
    '  entries: {',
    table,
    '  },',
    '};',
    '',
  ].join('\n');
}

const EMPTY_EDGE_MODULE = 'module.exports = { entries: {} };';
const EMPTY_WASM_MODULE = '// This deployment carries no WebAssembly.';
/**
 * A build told of no cache host: the runtime asks, is answered nothing, and runs as it did
 * before any cache existed. An export rather than an empty module, because the runtime imports
 * the name and a bundler must find it.
 */
const NO_CACHE_HOST_MODULE = 'export function createCacheHost() { return undefined; }';

/**
 * The generated modules the runtime source names: `ppr-cdn:app` is the `app.cjs` next to it in
 * the Worker, `ppr-cdn:edge` the `edge.cjs` — which a deployment with no edge entrypoint does
 * not have, and whose import is then the empty table above rather than a module the Worker would
 * carry and never use — and `ppr-cdn:wasm` the `wasm.mjs` that publishes the compiled
 * WebAssembly, which a deployment with none does not have either.
 *
 * `ppr-cdn:cache-host` is the one module of the four that comes from outside the build:
 * `cacheHostModule` names what the runtime's cache reads and writes through, and it is bundled
 * into the runtime rather than shipped beside it, since it is source like the rest of the
 * runtime. A build told of none resolves to the stub above.
 */
function generatedModulesPlugin(has: {
  edge: boolean;
  wasm: boolean;
  cacheHostModule: string | undefined;
}): Plugin {
  return {
    name: 'ppr-cdn-generated-modules',
    setup(bundler) {
      // eslint-disable-next-line require-unicode-regexp -- an esbuild filter is a Go regular expression
      bundler.onResolve({ filter: /^ppr-cdn:app$/ }, () => {
        return {
          path: `./${APP_MODULE}`,
          external: true,
        };
      });
      // eslint-disable-next-line require-unicode-regexp -- an esbuild filter is a Go regular expression
      bundler.onResolve({ filter: /^ppr-cdn:edge$/ }, () => {
        return has.edge
          ? { path: `./${EDGE_MODULE}`, external: true }
          : { path: 'ppr-cdn:edge', namespace: 'ppr-cdn-edge' };
      });
      bundler.onLoad(
        // eslint-disable-next-line require-unicode-regexp -- an esbuild filter is a Go regular expression
        { filter: /^ppr-cdn:edge$/, namespace: 'ppr-cdn-edge' },
        () => ({ contents: EMPTY_EDGE_MODULE, loader: 'js' }),
      );
      // eslint-disable-next-line require-unicode-regexp -- an esbuild filter is a Go regular expression
      bundler.onResolve({ filter: /^ppr-cdn:wasm$/ }, () => {
        return has.wasm
          ? { path: `./${WASM_ENTRY_MODULE}`, external: true }
          : { path: 'ppr-cdn:wasm', namespace: 'ppr-cdn-wasm' };
      });
      bundler.onLoad(
        // eslint-disable-next-line require-unicode-regexp -- an esbuild filter is a Go regular expression
        { filter: /^ppr-cdn:wasm$/, namespace: 'ppr-cdn-wasm' },
        () => ({ contents: EMPTY_WASM_MODULE, loader: 'js' }),
      );
      // eslint-disable-next-line require-unicode-regexp -- an esbuild filter is a Go regular expression
      bundler.onResolve({ filter: /^ppr-cdn:cache-host$/ }, () => {
        return has.cacheHostModule === undefined
          ? { path: 'ppr-cdn:cache-host', namespace: 'ppr-cdn-cache-host' }
          : { path: has.cacheHostModule };
      });
      bundler.onLoad(
        // eslint-disable-next-line require-unicode-regexp -- an esbuild filter is a Go regular expression
        { filter: /^ppr-cdn:cache-host$/, namespace: 'ppr-cdn-cache-host' },
        () => ({ contents: NO_CACHE_HOST_MODULE, loader: 'js' }),
      );
    },
  };
}

function runtimeEntry(): string {
  return fileURLToPath(import.meta.resolve('@upwind/runtime/worker'));
}

/** What the app bundle is built against: the rewrites it applies, and what it may resolve. */
export interface AppBundleContext {
  readonly patch: PatchContext;
  readonly wasm: WasmCollector;
}

/** What `bundleApp` collects as Rolldown runs, for the dependency record. */
export interface AppBundleSinks {
  readonly patches: AppliedPatch[];
  readonly stubs: string[];
  readonly externals: Set<string>;
  /** `.wasm` files the bundler resolved itself, as `<file> -> <global>`. */
  readonly wasm: string[];
}

/**
 * Every plugin an app bundle is built with, named in one place.
 *
 * Each of these is the reason something that would otherwise fail the build or the Worker does
 * not, or the reason the audit knows what it knows: a Next.js file rewritten, a module-loader
 * hook emptied, an optional package resolved to the copy Next.js ships, and the built-ins left
 * to the Worker reported as they resolve. Dropping one is silent — the bundle still builds, and
 * what it broke shows up in a customer's build or in their running Worker — so the set is
 * asserted by name. (The loads the bundler could not follow are read off what it rendered, not
 * collected as it runs: see `dynamicLoadsInChunk`.)
 */
export function appBundlePlugins(
  context: AppBundleContext,
  sinks: AppBundleSinks,
): RolldownPlugin[] {
  return [
    patchesPlugin(PATCHES, context.patch, (applied) => {
      sinks.patches.push(applied);
    }),
    stubPlugin((specifier) => {
      sinks.stubs.push(specifier);
    }),
    wasmModulePlugin(context.wasm, (file, global) => {
      sinks.wasm.push(`${file} -> ${global}`);
    }),
    vendoredOtelPlugin(),
    externalsPlugin((specifier) => sinks.externals.add(specifier)),
  ];
}

/**
 * How the app Worker's code is bundled: with the plugins above, and everything left to the
 * Worker's own resolver reported — a module Rolldown cannot resolve, which it leaves to the
 * Worker as it would a built-in, with a log, is recorded as an external too, for the audit to
 * refuse, which is what esbuild's refusal to build came to. Nothing else Rolldown has to say
 * reaches the build's output.
 */
export function appBundleOptions(
  projectDir: string,
  entryFile: string,
  context: AppBundleContext,
  sinks: AppBundleSinks,
): InputOptions {
  return {
    cwd: projectDir,
    input: entryFile,
    // Node built-ins, with or without the `node:` prefix, are the Worker's own to resolve.
    platform: 'node',
    plugins: appBundlePlugins(context, sinks),
    transform: {
      define: {
        'process.env.NEXT_RUNTIME': '"nodejs"',
        'process.env.NODE_ENV': '"production"',
      },
    },
    onLog(_level, log) {
      if (log.code === 'UNRESOLVED_IMPORT' && log.exporter !== undefined) {
        sinks.externals.add(log.exporter);
      }
    },
  };
}

/**
 * The app Worker's code: Next.js's CommonJS output, bundled by Rolldown into one CommonJS module
 * with the patches applied as each file is loaded. Rolldown's output is 5% smaller than esbuild's
 * for the same graph and comes 40% sooner (see EXPERIMENTS.md, V-03); the runtime bundle stays
 * on esbuild for its `workerd` conditions. Whitespace and syntax are minified, names are not:
 * the audit reads them.
 */
async function bundleApp(
  input: BuildWorkerInput,
  workDir: string,
): Promise<{ outFile: string; trace: BundleTrace }> {
  const entryFile = path.join(workDir, `${input.kind}-entry.cjs`);
  const outFile = path.join(workDir, `${input.kind}-${APP_MODULE}`);
  await writeFile(entryFile, appEntrySource(input.entries));
  const sinks: AppBundleSinks = { patches: [], stubs: [], externals: new Set(), wasm: [] };
  await using bundle = await rolldown(
    appBundleOptions(input.projectDir, entryFile, { patch: input.patch, wasm: input.wasm }, sinks),
  );
  const { output } = await bundle.write({
    format: 'cjs',
    file: outFile,
    // One file, so an `import()` the bundler can follow — `@vercel/og`'s edge build, which the
    // `vercel-og` patch turns Turbopack's external into — is inlined into it rather than split
    // out into a chunk the Worker would have to load. It stays lazy: the module it names is
    // wrapped in an initializer the `import()` runs, so the library is evaluated by the first
    // request that renders an image and by no other.
    codeSplitting: false,
    banner: WORKER_BANNER,
    minify: { compress: true, mangle: false, codegen: { removeWhitespace: true } },
    comments: { legal: false },
    // The build already ran; there is nothing to watch and no sourcemap consumer in the Worker.
    sourcemap: false,
  });
  const chunk = output.find((item): item is OutputChunk => item.type === 'chunk');
  if (chunk === undefined) {
    throw new Error(`@upwind/adapter: the ${input.kind} Worker bundled to no chunk`);
  }
  return {
    outFile,
    trace: {
      inputs: Object.entries(chunk.modules).map(([file, module]) => bundled(file, module)),
      externals: [...sinks.externals],
      patches: sinks.patches,
      stubs: sinks.stubs,
      wasmModules: sinks.wasm,
      dynamicLoads: dynamicLoadsInChunk(chunk),
    },
  };
}

async function bundleRuntime(input: BuildWorkerInput, workDir: string): Promise<string> {
  const outFile = path.join(workDir, `${input.kind}-${RUNTIME_MODULE}`);
  await build({
    entryPoints: [runtimeEntry()],
    bundle: true,
    platform: 'node',
    format: 'esm',
    target: 'es2024',
    outfile: outFile,
    external: ['node:*', 'cloudflare:*'],
    conditions: ['workerd', 'worker'],
    plugins: [
      generatedModulesPlugin({
        edge: input.edgeEntries.length > 0,
        wasm: input.wasm.hasCandidates,
        cacheHostModule: input.cacheHostModule,
      }),
    ],
    define: {
      'process.env.NODE_ENV': '"production"',
      __ARKOR_WORKER_KIND__: JSON.stringify(input.kind),
      // CommonJS conveniences that `@next/routing`'s build references at module scope.
      __dirname: '"/bundle"',
      __filename: `"/bundle/${RUNTIME_MODULE}"`,
    },
    minify: false,
    legalComments: 'none',
    logLevel: 'silent',
    sourcemap: false,
  });
  return outFile;
}

export interface BuiltWorker {
  readonly spec: WorkerSpec;
  readonly dependencies: WorkerDependencies;
}

const WASM_LOADER_PATCH = 'wasm-loader';
const OG_FONT_PATCH = 'vercel-og-font';

/**
 * What the Worker weighs, as Cloudflare weighs it: the modules it will be uploaded with, through
 * one gzip stream. One stream rather than one per module, because that is how the upload is
 * compressed, and a `.wasm` next to a bundle of the same library compresses with it.
 */
async function workerSize(outDir: string, modules: readonly WorkerModule[]): Promise<WorkerSize> {
  // What each module weighs is already on its blob; only the compressed size needs the bytes.
  const bytes = modules.reduce((total, module) => total + module.blob.byteLength, 0);
  const blobs = path.join(outDir, 'blobs');
  const gzip = createGzip();
  let gzipBytes = 0;
  let failure: unknown;
  gzip.on('data', (chunk: Buffer) => {
    gzipBytes += chunk.byteLength;
  });
  // A stream with no `error` listener takes the process down with it, and this one spends most of
  // its life waiting on a read; `once` only listens while it is awaited.
  gzip.on('error', (error: unknown) => {
    failure ??= error;
  });
  try {
    for (const module of modules) {
      const content = await readFile(path.join(blobs, module.blob.sha256));
      if (!gzip.write(content)) {
        await once(gzip, 'drain');
      }
    }
    gzip.end();
    await once(gzip, 'end');
  } finally {
    gzip.destroy();
  }
  if (failure !== undefined) {
    throw new Error(`@upwind/adapter: could not measure the Worker`, { cause: failure });
  }
  return { bytes, gzipBytes };
}

/**
 * The bytes of `next/og`'s fallback font, read from the very file the patch was applied to, or
 * `undefined` when this bundle carries no `@vercel/og` at all. Reading it off the patched file's
 * own directory is what keeps the two in step: the font that travels is the one that library
 * would have read.
 */
async function ogFallbackFont(applied: readonly AppliedPatch[]): Promise<Uint8Array | undefined> {
  const patched = applied.find((item) => item.patch === OG_FONT_PATCH);
  if (patched === undefined) {
    return undefined;
  }
  const font = path.join(path.dirname(patched.file), OG_FONT_FILE);
  return new Uint8Array(await readFile(font));
}

/**
 * The one patch that finds its file by what is in it rather than by its name, held to the same
 * word as the others: a build whose Node.js entrypoints bundle WebAssembly must have rewritten
 * Turbopack's loader. Without this, a loader that moved somewhere the patch does not look leaves
 * a Worker that reads a `.wasm` off a file system it does not have, and says so on the first
 * request rather than here.
 *
 * The other way round is not a mismatch: a Worker may bundle the loader from a chunk it shares
 * with something else while none of its own entrypoints reaches WebAssembly, and the table the
 * patch leaves is then empty and never asked.
 */
function auditWasmLoader(
  kind: string,
  patch: PatchContext,
  applied: readonly AppliedPatch[],
): void {
  if (patch.wasm.length === 0) {
    return;
  }
  if (applied.every((item) => item.patch !== WASM_LOADER_PATCH)) {
    throw new Error(
      `@upwind/adapter: the ${kind} Worker's entrypoints bundle WebAssembly (${patch.wasm
        .map((item) => item.chunkPath)
        .join(', ')}) but no Turbopack WebAssembly loader was found to rewrite`,
    );
  }
}

/**
 * Bundle one Worker and register its modules as blobs: the upload specification, and the record
 * of what went into it — audited, so a Worker that would not run fails the build.
 */
export async function buildWorker(input: BuildWorkerInput): Promise<BuiltWorker> {
  const workDir = path.join(input.outDir, 'work');
  await mkdir(workDir, { recursive: true });
  const [app, runtimeFile, edge] = await Promise.all([
    bundleApp(input, workDir),
    bundleRuntime(input, workDir),
    input.edgeEntries.length === 0
      ? undefined
      : bundleEdge({
          kind: input.kind,
          projectDir: input.projectDir,
          workDir,
          entries: input.edgeEntries,
        }),
  ]);
  const appFile = app.outFile;
  const modules: WorkerModule[] = [
    {
      name: RUNTIME_MODULE,
      type: 'esm',
      blob: await input.blobStore.putFile(runtimeFile, contentTypeFor(runtimeFile)),
    },
    {
      name: APP_MODULE,
      type: 'commonjs',
      blob: await input.blobStore.putFile(appFile, contentTypeFor(appFile)),
    },
    ...(edge === undefined
      ? []
      : [
          {
            name: EDGE_MODULE,
            type: 'commonjs' as const,
            blob: await input.blobStore.putFile(edge.outFile, contentTypeFor(edge.outFile)),
          },
        ]),
    {
      name: RUNTIME_MANIFEST_MODULE,
      type: 'text',
      blob: await input.blobStore.putText(input.runtimeManifest, 'application/json'),
    },
  ];
  for (const manifest of input.manifests) {
    modules.push({
      name: manifest.name,
      type: 'text',
      blob: await input.blobStore.putText(manifest.contents, contentTypeFor(manifest.name)),
    });
  }
  for (const blob of input.blobs) {
    modules.push({
      name: blobModuleName(blob.sha256),
      type: 'data',
      blob: await input.blobStore.put(blob.bytes, 'application/octet-stream'),
    });
  }
  const wasmModules = input.wasm.modules;
  // Whenever the runtime bundle was built with a `./wasm.mjs` to import — which is decided
  // before the app bundle has resolved its `?module` imports — the module has to be there, even
  // if in the end nothing read any of the WebAssembly the traces offered.
  if (input.wasm.hasCandidates) {
    modules.push({
      name: WASM_ENTRY_MODULE,
      type: 'esm',
      blob: await input.blobStore.putText(wasmEntrySource(wasmModules), 'text/javascript'),
    });
    for (const module of wasmModules) {
      modules.push({
        name: wasmModuleName(module.sha256),
        type: 'wasm',
        blob: await input.blobStore.put(module.bytes, 'application/wasm'),
      });
    }
  }
  // `next/og`'s fallback font, when the bundle carries the library that reads it. Only then: it
  // is 126 KiB an application that renders no image never has to carry.
  const font = await ogFallbackFont(app.trace.patches);
  if (font !== undefined) {
    modules.push({
      name: OG_FONT_MODULE,
      type: 'data',
      blob: await input.blobStore.put(font, 'font/ttf'),
    });
  }
  const { distDir } = input.patch;
  const size = await workerSize(input.outDir, modules);
  const dependencies: WorkerDependencies = {
    ...workerDependencies(input.projectDir, distDir, app.trace, { modules, size }),
    ...(edge !== undefined && {
      edge: bundleDependencies(input.projectDir, distDir, edge.trace),
    }),
  };
  auditWasmLoader(input.kind, input.patch, app.trace.patches);
  auditWorkerSize(input.kind, { modules, size });
  auditWorker(
    input.kind,
    {
      app: await readFile(appFile, 'utf8'),
      ...(edge !== undefined && { edge: await readFile(edge.outFile, 'utf8') }),
    },
    dependencies,
  );
  return {
    spec: {
      mainModule: RUNTIME_MODULE,
      modules,
      compatibilityDate: WORKER_COMPATIBILITY_DATE,
      compatibilityFlags: [...WORKER_COMPATIBILITY_FLAGS],
    },
    dependencies,
  };
}
