import type { IncomingMessage, ServerResponse } from 'node:http';

/** The Node.js entrypoint handler `next build` emits (see `next/dist/build/templates/app-page.ts`). */
export type NodeHandler = (
  req: IncomingMessage,
  res: ServerResponse,
  ctx: {
    waitUntil?: (promise: Promise<unknown>) => void;
    requestMeta?: Record<string, unknown>;
  },
) => Promise<unknown>;

/**
 * A handler that takes a Web `Request`: the middleware's, whichever runtime it was built for
 * (`next/dist/build/templates/middleware.ts` is the source of both), and every entrypoint on the
 * edge runtime (`edge-ssr-app.ts`, `edge-app-route.ts`, `pages-edge-api.ts`).
 */
export type WebHandler = (
  request: Request,
  ctx: {
    waitUntil?: (promise: Promise<unknown>) => void;
    signal?: AbortSignal;
    requestMeta?: Record<string, unknown>;
  },
) => Promise<Response>;

interface EntryModule {
  readonly handler: NodeHandler | WebHandler;
}

interface EdgeEntryModule {
  readonly handler: WebHandler;
}

/**
 * What `app.cjs` (generated by the adapter) exports. A thunk hands back a promise of its module
 * rather than the module when the entrypoint's source has a top-level await, so what comes out of
 * one is awaited before its handler is read (`entries.ts`).
 */
export interface AppModule {
  readonly entries: Readonly<Record<string, () => EntryModule | Promise<EntryModule>>>;
}

/**
 * What `edge.cjs` exports, when the build put entrypoints on the edge runtime: the same table of
 * thunks, each evaluating that entrypoint's chunks and handing back the handler they registered.
 * A deployment without one gets an empty table from the adapter, so nothing here is optional.
 */
export interface EdgeModule {
  readonly entries: Readonly<Record<string, () => EdgeEntryModule | Promise<EdgeEntryModule>>>;
}
