/** Which Function this runtime was bundled into; the adapter sets it with an esbuild `define`. */
// eslint-disable-next-line @typescript-eslint/naming-convention -- an esbuild define, named as such
declare const __ARKOR_FUNCTION_KIND__: 'app' | 'middleware';

/** `app.cjs`, generated by the adapter next to the runtime; esbuild rewrites the specifier. */
declare module 'arkor:app' {
  import type { AppModule } from './app-module.ts';

  const app: AppModule;
  export default app;
}

/** `edge.cjs`, the same for the edge runtime's entrypoints; an empty table when there are none. */
declare module 'arkor:edge' {
  import type { EdgeModule } from './app-module.ts';

  const edge: EdgeModule;
  export default edge;
}

/**
 * `wasm.mjs`, which imports every WebAssembly module the Function carries and publishes each under
 * the names that read it. It exports nothing: importing it is the whole of what it does.
 */
declare module 'arkor:wasm' {}

/**
 * The cache this deployment takes part in, if it takes part in one: the module the adapter was
 * told to resolve this to (`cacheHostModule`), or the stub that answers `undefined` when it was
 * told of none. A build with no host runs as the runtime did before any cache existed.
 */
declare module 'arkor:cache-host' {
  import type { BundleBlobsExport } from './bundle-blobs.ts';
  import type { CacheHostInit, CacheHostLookup } from './cache/host.ts';

  /** The host these bindings reach, or nothing when they name none. */
  export function createCacheHost(init: CacheHostInit): CacheHostLookup;

  /**
   * One blob of this deployment's own bundle, for a host that keeps a build's outputs itself and
   * has the adapter leave some of them out of the Function (`AdapterOptions.unshippedOutputs`).
   *
   * Optional, and read through a namespace import (`function.ts`): a host module that exports none
   * ships every blob, which is every build that does not ask for otherwise.
   */
  export const createBundleBlobReader: BundleBlobsExport;
}

/**
 * workerd's bridge from a Web `Request` to the `node:http` server the Function listens on
 * (`enable_nodejs_http_server_modules`, on by default from compatibility date 2025-09-01).
 * Wrangler's generated types name only `httpServerHandler`; this is the function underneath it.
 */
declare module 'cloudflare:node' {
  /**
   * Hands `request` to the server listening on `port` and resolves with its response once the
   * headers are committed; the body streams. `env` and `ctx` are attached to the incoming
   * message as `req.cloudflare = { env, ctx }`, whatever they are.
   */
  export function handleAsNodeRequest(
    port: number,
    request: Request,
    env?: unknown,
    ctx?: unknown,
  ): Promise<Response>;
}

/**
 * The environment the Function is handed, importable from anywhere in it — at a module's top level
 * too, where I/O through a binding still has to wait for a request. What the runtime publishes the
 * application's storage bindings from before its first request (`resources.ts`).
 */
declare module 'cloudflare:workers' {
  export const env: unknown;
}
